services:

  redis:
    container_name: redis_service
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - vehicle
  ignite:
    container_name: ignite_service
    image: apacheignite/ignite
    restart: unless-stopped
    ports:
      - 10800:10800
    networks:
      - vehicle

  # POC Application using apache inginte , redis caching 
  # APACHE_IGNITE
  # REDIS
  backend:
    image: caching-poc:latest
    restart: unless-stopped
    environment:
      QUARKUS_REDIS_URL: redis://redis:6379
      QUARKUS_IGNITE_URL: ignite:10800
      CACHE_CLIENT: REDIS
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - ignite
    networks:
      - vehicle


networks:
  vehicle:
    name: quarkus-caching-poc-demo
    driver: bridge

